sonar.projectKey=a1351995160_yungateway-minimal-token-wps
sonar.projectName=yungateway-minimal-token-wps
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.pmd.reportPaths=target/pmd.xml
sonar.sourceEncoding=UTF-8
